config/routes.rb
Rails.application.routes.draw do
  get 'portfolio/index'
  get 'overview/index'

  root 'overview#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def build_active_link(label)
        label.to_s do
            concat content_tag(:span, "(current)", :class => 'sr-only')
        end
    end
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketdataViewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "Marketdata Viewer", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to build_active_link("Overview"), overview_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Portfolio", portfolio_index_path, class: "nav-link" %>
            </li>
          <ul>
        </div>  
      </div>
    </nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer>
  </footer>
  
  </body>
  <%= javascript_pack_tag 'application' %>
</html>

app/views/overview/index.html.erb
<h3>Overview</h3>

app/views/portfolio/index.html.erb
<h1>Portfolio#index</h1>
<p>Find me in app/views/portfolio/index.html.erb</p>